[package]
name = "paid-counter-account"
version = "0.1.0"

[lib]
kind = "account-component"
namespace = "miden:paid-counter-account/paid-counter@0.1.0"

[dependencies]
miden-core = "*"
miden-protocol = "*"

[package.metadata.miden]
supported-types = ["RegularAccountImmutableCode"]
